### ISSUE TITLE
DELETE Job error

### ISSUE THREAD

**Issue by mfigurski80** [DonateComputing/DonateAPI#7]
Running this...
```
http -a miko:pass DELETE localhost:8080/miko

http: error: ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing DELETE request to URL: http://localhost:8080/miko
```
...causes server to log this...
```
2020/09/30 19:36:49 http: panic serving 172.17.0.1:53914: assignment to entry in nil map
goroutine 27 [running]:
net/http.(*conn).serve.func1(0xc0000d0140)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x6a96a0, 0x745680)
	/usr/local/go/src/runtime/panic.go:975 +0x3e9
github.com/mfigurski80/DonateAPI/api.deleteUser(0x74e5a0, 0xc0000a8700, 0xc000099f00)
	/app/api/routerUser.go:94 +0x32e
```

**Comment by mfigurski80** [comment]
This is actually trying to delete a user, so it's likely a duplicate of issue #9
