### ISSUE TITLE
DELETE user fails

### ISSUE THREAD

**Issue by mfigurski80** [DonateComputing/DonateAPI#9]
On a DELETE request to user...

```
2020/09/30 19:35:53 http: panic serving 172.17.0.1:53900: assignment to entry in nil map
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc0000d0000)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x6a96a0, 0x745680)
	/usr/local/go/src/runtime/panic.go:975 +0x3e9
github.com/mfigurski80/DonateAPI/api.deleteUser(0x74e5a0, 0xc0001348c0, 0xc00015b300)
	/app/api/routerUser.go:94 +0x32e
net/http.HandlerFunc.ServeHTTP(0x7093e8, 0x74e5a0, 0xc0001348c0, 0xc00015b300)
	/usr/local/go/src/net/http/server.go:2042 +0x44
```

**Comment by mfigurski80** [comment]
Similar to #6, #7, #8, these issues were resolved on the client side. However, it's very possible that these are the fail states for when DELETEing a user / job that doesn't exist. Needs further investigation
